- name: Debian and Ubuntu setup
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - packages.yml
  
  tasks:
    - name: Install apt packages
      apt:
        pkg: "{{ apt_packages }}"
        update_cache: yes
    - name: Install snap packages
      community.general.snap:
        name: "{{ snap_packages }}"
        state: present
        
