- name: macOS setup
  hosts: localhost
  connection: local
  vars_files:
    - packages.yml

  pre_tasks:
    - name: Check if Homebrew is installed
      ansible.builtin.command: brew --version
      register: version
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: version.rc != 0 # rc is for return code
  
  tasks:
    - name: Tap Homebrew repositories
      include_tasks: task_homebrew_tap.yml
      vars:
        tap: "{{ item }}"
      with_items:
        - "{{ taps }}"

    - name: Install Homebrew formula packages
      include_tasks: task_homebrew_formula.yml
      vars:
        formula: "{{ item }}"
      with_items:
        - "{{ formulae }}"

    - name: Install Homebrew cask packages
      include_tasks: task_homebrew_cask.yml
      vars:
        cask: "{{ item }}"
      with_items:
        - "{{ casks }}"

  post_tasks:
    - name: Report any errors
      debug:
        var: ansible_failed_task
      when: ansible_failed_task is defined