- name: macOS setup
  hosts: localhost
  connection: local
  vars_file:
    - /packages.yml

  pre_tasks:
    - name: Check if homebrew is installed
      ansible.builtin.command: brew --version
      register: version
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: version.rc != 0 # rc is for return code
  
  tasks:
    - name: Tap a Homebrew repository, state present
      community.general.homebrew_tap:
        name: "{{ taps }}"

    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ formulae }}"
        state: present
        update_homebrew: true

    - name: Install homebrew cask packages
      community.general.homebrew_cask:
        name: "{{ casks }}"
        state: present
        update_homebrew: true

  post_tasks:
    - name: Report any errors
      debug:
        var: ansible_failed_task
      when: ansible_failed_task is defined