- name: macOS setup
  hosts: localhost
  connection: local
  vars_file:
    - /packages.yml

  pre_tasks:
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not ('brew' in ansible_playbook_python)
  
  tasks:
    - name: Add homebrew taps
      command: brew tap {{ item }}
      loop: "{{ taps }}"

    - name: Update homebrew
      homebrew:
        update_homebrew: true

    - name: Install homebrew packages
      homebrew:
        name: "{{ item }}"
        state: latest
      loop: "{{ formulae }}"

    - name: Install homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
        state: latest
      loop: "{{ casks }}"
      ignore_errors: true

    - name: homebrew cleanup
      command: brew cleanup

  post_tasks:
    - name: Report any errors
      debug:
        var: ansible_failed_task
      when: ansible_failed_task is defined